### ISSUE TITLE
Text correction

### ISSUE THREAD

**Issue by lomohov** [prosteSebastian/ma-for-dummies.github.io#2]
![image](https://user-images.githubusercontent.com/92575860/232473165-5c7c94ea-9e8e-4a9e-9b7d-11558e7b999b.png)

Vždycke -> Vždy/Vždycky

nebo-li -> neboli (případně nahradit za "resp.")
https://prirucka.ujc.cas.cz/?id=164
Spojovník - odstavec 3
> Dalším uplatněním spojovníku je připojení spojky ‑li. Ta se připojuje zpravidla ke slovesu stojícímu na začátku věty (víš‑li, říkám‑li, mohl‑li), někdy k částici ne (ne‑li), případně k jinému výrazu (lze‑li). Avšak pokud je ‑li pouze součástí složené spojky, spojovník nepíšeme (zdali, čili, jestli, neboli, pakliže, nežli, ačli).

**Comment by prosteSebastian** [comment]
diky, done
