### ISSUE TITLE
Improvement suggestion & typos

### ISSUE THREAD

**Issue by lomohov** [prosteSebastian/ma-for-dummies.github.io#3]
upráva -> úprava
zda-li -> zdali pro vysvětlení viz issue #2  

![image](https://user-images.githubusercontent.com/92575860/232474273-b471e7a9-9fe9-44e4-9eb9-b2e6dcd9fa26.png)

Co vůbec znamená "úprava o vynásobení vhodnou jedničkou"?

Navrhuji nahradit větu za: 

Zde je důležité si uvědomit, zdali nám úprava tzv. *vynásobení vhodnou jedničkou* pomůže.

**Comment by prosteSebastian** [comment]
fixed
