### ISSUE TITLE
Odd listing of arctan limit

### ISSUE THREAD

**Issue by lomohov** [prosteSebastian/ma-for-dummies.github.io#4]
![image](https://user-images.githubusercontent.com/92575860/232475862-7fffb3c7-0b99-4a74-b60a-92618b7153d8.png)

Je limita arctan x-> inf arctan(x) opravdu odvozena ze součtových vzorců (jakých součtových vzorců? Kde zmíněno?) sinu a cosinu?

Zároveň navrhuji přidat limitu x-> -inf arctan(x)

**Comment by prosteSebastian** [comment]
to bylo smisleno jen jako vec, ve ktere se dost chybuje, muzu k tomu pridat poznamku :+1:
