### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by stepech** [prosteSebastian/ma-for-dummies.github.io#6]

**Comment by stepech** [comment]
K čemu jsou tam ty linky když nejsou proklikávací ani koírovatelný?

**Comment by prosteSebastian** [comment]
ciste design, importuji to z obsidianu, kde to slouzi jako tag.

**Comment by prosteSebastian** [comment]
az zjistim, jak se to dela, tak to predelam na actually prolinky :+1:
